<a href="https://colab.research.google.com/github/Uwais-ur-Rehman/ML-Project/blob/main/First_day_of_Coding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task

Task:1
Profile Card (Variables + Types)

In [ ]:
name="Uwais ur Rehman"
age=21
cgpa=3.31
is_enrolled="true"
print(f"Hello my name is {name}  I am {age} old and and I have secured {cgpa} CGPA my enrollment status is {is_enrolled} ")

Hello my name is Uwais ur Rehman  I am 21 old and and I have secured 3.31 CGPA my enrollment status is true

Task:2
Billing Calculator (Arithmetic Operators)

In [ ]:
price= 2499
qty=3
discount_percent=10
tax_percent=5
subtotal=price*qty
discount_amount= subtotal*(discount_percent/100)
after_discount= subtotal-discount_amount
tax_amount= after_discount*(tax_percent/100)
print(f"The Subtotal is {subtotal}")
print(f"The Discount is {discount_amount}")
print(f"The Total after discount is {after_discount}")
print(f"The tax amount {tax_amount}")

The Subtotal is 7497
The Discount is 749.7

Task:3
Split Seconds (// and %)

In [ ]:
total_second=7384
hours=total_second//3600
minutes=total_second//60
second=total_second%60
print(f"Hours {hours} , minutes {minutes} and second {second}")

Hours 2 , minutes 123 and second 4

Task:*4*
String Slicing Drill (Indexing + Slicing)

In [ ]:
s="Python Programming"
print(f"The first Character of the string is: {s[0]}")
print(f"The last Character of the string is: {s[-1]}")
print(f"To print the word 'Python' from the '{s}': {s[0:6]}")
print(f"To print the word 'Programming' from the '{s}': {s[-11:]}")

The first Character of the string is: P
The last Character of the string is: g
To print the word 'Python' from the 'Python Programming': Python
To print the word 'Programming' from the 'Python Programming': Programming

Task:5
Clean & Normalize Input (String Methods)

In [ ]:
name=" Uwais ur Rehman "
trimmed=name.strip()
print(f"The trimmed name: {name}")
lower_name=trimmed.lower()
print(f"The lower case name is: {lower_name}")
title_name=trimmed.title()
print(f"The title case name is: {title_name}")
replace_name=trimmed.replace("Re","Ra")
print(f"The replaced name is: {replace_name}")

The trimmed name:  Uwais ur Rehman
The lower case name is: uwais ur rehman
The title case name is: Uwais Ur Rehman
The replaced name is: Uwais ur Rahman

Task 6
 Create a NumPy array of integers from 1 to 20. Compute the mean, maximum, and
standard deviation.
Hint: Look at NumPy statistical functions.
Must Use: numpy.mean(), numpy.max(), numpy.std()

In [ ]:
import numpy as np
nbr= np.arange(1,21)
mean_value=np.mean(nbr)
max_value=np.max(nbr)
std_value=np.std(nbr)
print(nbr)
print(f"The mean value is: {mean_value}")
print(f"The max value is: {max_value}")
print(f"The std value is: {std_value}")

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
The mean value is: 10.5
The max value is: 20
The std value is: 5.766281297335398

Task 7
 Create a 5×5 random matrix and replace all values less than 0.5 with 0.
Hint: Boolean masking is useful here.
Must Use: numpy.random.rand(), boolean indexing

In [ ]:
import numpy as np
mat=np.random.rand(5,5)
print(f"Origiol mat {mat}" )

Origiol mat [[0.11588282 0.71084633 0.67929351 0.92748251 0.50968571]
 [0.16332907 0.7365105  0.72667646 0.1122705  0.51227468]
 [0.90549384 0.44817094 0.40582185 0.38189759 0.99524835]
 [0.68465821 0.07366202 0.25200286 0.46954105 0.22568625]
 [0.54374925 0.28833923 0.50035933 0.15480844 0.45535428]]

Tuple and List

In [ ]:
fruits_tuple=("oranges",12,"apple",2 ,"mango",2)
print(f"Tuple = {fruits_tuple}")

fruits_list=["grapes",3,"banana",12,"watermelon",5]
fruits_list.append("Cherry")
fruits_list.append(6)
fruits_list[1]=2

print("Lists = ",fruits_list)
fruits_list.pop(7)
fruits_list.remove("Cherry")
print(fruits_list)

Tuple = ('oranges', 12, 'apple', 2, 'mango', 2)
Lists =  ['grapes', 2, 'banana', 12, 'watermelon', 5, 'Cherry', 6]
['grapes', 2, 'banana', 12, 'watermelon', 5]

Dictionaries

In [ ]:
student={
    "Name":"Uwais ur Rehman",
    "Father_Name":"Atta ur Rehman",
    "Age":21

    }
student["Gender"]="Male"
print(student)
print(f"The Name of the Student is {student.get("Name")}")
print(f"The Age of the Student is {student["Age"]}")

{'Name': 'Uwais ur Rehman', 'Father_Name': 'Atta ur Rehman', 'Age': 21, 'Gender': 'Male'}
The Name of the Student is Uwais ur Rehman
The Age of the Student is 21

If else condition

In [ ]:
marks=int(input("Enter your marks"))
if marks>85:
  print("Grade A")
elif marks>=75:
  print("Grade B")
elif marks>=65:
  print("Grade C")
elif marks>=50:
  print("Grade D")
else:
  print("Fail")

Enter your marks76
Grade B

Function

In [ ]:
def sum(a,b):
  return a+b

num1=int(input("Enter first number"))
num2=int(input("Enter second number"))
#result=sum(num1,num2)
print(f"The sum of the two entered number is {sum(num1,num2)}")

Enter first number22
Enter second number221
The sum of the two entered number is 243

Error Handling

In [ ]:
try:
  Name=input("Enter your name ")
  Semester=int(input("Enter your semester "))
  total_sub=int(input(f"Enter total number of subject in semester {Semester}     "))
  total_marks=0
  for i in range(total_sub):
    marks=int(input(f"Enter marks for subject  {i+1}   "))
    if marks<0 or marks>100:
      raise ValueError("Marks must be between 0 and 100")
    total_marks+=marks
  percentage=total_marks/(total_sub*100)*100

except ValueError as ae:
  print("Value Error ")
except Exception as e:
  print("Error occured")

else:
  print("\n")
  print(f"Name:  {Name}")
  print(f"Semester:  {Semester}")
  print(f"Total Marks:  {total_marks} out of {total_sub*100}")
  print(f"Percentage:  {percentage}%98")
  if percentage>85:
    print("Grade A:")
  elif percentage>=75:
    print("Grade B:")
  elif percentage>=65:
    print("Grade C:")
  elif percentage>=50:
    print("Grade D:")
  else:
    print("Fail")
finally:
  print("Program executed sucessfully7")

Enter your name Uwais ur Rehman
Enter your semester 7
Enter total number of subject in semester 7     4
Enter marks for subject  1   89
Enter marks for subject  2   91
Enter marks for subject  3   78
Enter marks for subject  4   79


Name:  Uwais ur Rehman
Semester:  7
Total Marks:  337 out of 400
Percentage:  84.25%
Grade B:
Program executed sucessfully7

Set

In [ ]:
setA={1,2,3,"ahmad",3,"ahmad"}
if 'ahmad' in setA:
  print("ahmad is present")
print(setA)

ahmad is present
{1, 2, 3, 'ahmad'}

Numpy

In [ ]:
import numpy as np
numpy_arry1= np.array([1,2,3,4])
numpy_arry2= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
numpy_arry3=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
                      [[13,14,15,16],[17,18,19,20],[21,21,22,23]]])
print(f"The data type fo the numpy_arry1 is {numpy_arry1.dtype}")
print(f"Shape of the numpy_arry1 is {numpy_arry1.shape}")
print(f"Shape of the numpy_arry3 is {numpy_arry3.shape}")
print(f"Size of the numpy_arry3 is {numpy_arry3.size}")
print(f"Dimension of the numpy_arry3 is {numpy_arry3.ndim}")
print(numpy_arry1)
print(numpy_arry2)
print(numpy_arry3)


zeros= np.zeros((3,3),dtype=int)
print(zeros)
print(zeros.ndim)

arr_r= np.arange(11)
print(arr_r)

arr_d=np.linspace(1,10,20)
print(arr_d)

The data type fo the numpy_arry1 is int64
Shape of the numpy_arry1 is (4,)
Shape of the numpy_arry3 is (2, 3, 4)
Size of the numpy_arry3 is 24
Dimension of the numpy_arry3 is 3
[1 2 3 4]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 21 22 23]]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
2
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]

Arithematic Calculation on Matric

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([2,4,6])
arr3=arr1+arr2
print(f"Sum of two arrays is {arr3}")

arr3+=4
print(f"Sum of result array with a scalar '4' {arr3}")
print(f"Product of result array with a scalar '4' {arr3*4}")

arr4=np.array([[10],[20],[30]])
print(f"The sum of one dim array with three dim is {arr3+arr4}")

Sum of two arrays is [3 6 9]
Sum of result array with a scalar '4' [ 7 10 13]
Product of result array with a scalar '4' [28 40 52]
The sum of one dim array with three dim is [[17 20 23]
 [27 30 33]
 [37 40 43]]

Reshape

In [ ]:
arr5= np.arange(12)
arr6=arr5.reshape(2,6)
print(arr6)

arr7=arr6.flatten() #Converts array to 1-D, Creates a NEW copy of the data and If you change array, original array does NOT change.
arr7[3]=70
print(f"Flatten using flatten {arr7}")

arr8=arr6.ravel() #Converts array to 1-D ,Does NOT create a new copy (view of original array) and If you change r, original array MAY change.
arr8[2]=49
print(f"Flatten using Ravel {arr8}")

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Flatten using flatten [ 0  1  2 70  4  5  6  7  8  9 10 11]
Flatten using Ravel [ 0  1 49  3  4  5  6  7  8  9 10 11]

Random Number

In [ ]:
arr9=np.random.randint(1,10,size=15)
print(arr9)

[1 9 1 1 7 9 3 6 6 4 9 5 5 6 8]

Indexing and Slicing

In [ ]:
import numpy as np
arr10=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(f"arr10 {arr10[1,2]}")
arr11=np.array([2,4,6])
print(f"array11 {arr11[-1]}")
print(arr11[-3])
arr10[2]=200
print(arr10)

arr10 6
array11 6
2
[[  1   2   3]
 [  4   5   6]
 [200 200 200]
 [ 10  11  12]]

In [ ]:
arr12=np.array([[[1,2,3,4,5],[6,7,8,9,10],[2,4,6,8,10],[1,3,5,7,9]],
                [[10,9,8,7,6],[5,4,3,2,1],[10,8,6,4,2],[9,7,5,3,1]],
                [[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3],[4,4,4,4,4]],
                [[5,5,5,5,5],[6,6,6,6,6],[7,7,7,7,7],[8,8,8,8,8]]])
print(arr12)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [ 2  4  6  8 10]
  [ 1  3  5  7  9]]

 [[10  9  8  7  6]
  [ 5  4  3  2  1]
  [10  8  6  4  2]
  [ 9  7  5  3  1]]

 [[ 1  1  1  1  1]
  [ 2  2  2  2  2]
  [ 3  3  3  3  3]
  [ 4  4  4  4  4]]

 [[ 5  5  5  5  5]
  [ 6  6  6  6  6]
  [ 7  7  7  7  7]
  [ 8  8  8  8  8]]]

In [ ]:
print(arr12[:2])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [ 2  4  6  8 10]
  [ 1  3  5  7  9]]

 [[10  9  8  7  6]
  [ 5  4  3  2  1]
  [10  8  6  4  2]
  [ 9  7  5  3  1]]]

In [ ]:
print(arr12[2:4])

[[[1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]
  [4 4 4 4 4]]

 [[5 5 5 5 5]
  [6 6 6 6 6]
  [7 7 7 7 7]
  [8 8 8 8 8]]]

In [ ]:
print(arr12[1:4:2,0:4:2])

[[[10  9  8  7  6]
  [10  8  6  4  2]]

 [[ 5  5  5  5  5]
  [ 7  7  7  7  7]]]

In [ ]:
import numpy as np
mat1=np.full((4,4,4),42)
mat1

array([[[42, 42, 42, 42],
        [42, 42, 42, 42],
        [42, 42, 42, 42],
        [42, 42, 42, 42]],

       [[42, 42, 42, 42],
        [42, 42, 42, 42],
        [42, 42, 42, 42],
        [42, 42, 42, 42]],

       [[42, 42, 42, 42],
        [42, 42, 42, 42],
        [42, 42, 42, 42],
        [42, 42, 42, 42]],

       [[42, 42, 42, 42],
        [42, 42, 42, 42],
        [42, 42, 42, 42],
        [42, 42, 42, 42]]])

In [ ]:
mat1.ndim

2

In [ ]:
mat1.shape

(4, 4)

In [ ]:
mat1[1,2]

np.int64(42)

In [ ]:
mt=mat1
mt[2,2]=100
mat1

array([[ 42,  42,  42,  42],
       [ 42,  42,  42,  42],
       [ 42,  42, 100,  42],
       [ 42,  42,  42,  42]])

In [ ]:
arr13=np.arange(0,16)
arr14=arr1.reshape(4,4)
print(arr14)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

In [ ]:
print(arr14[:,1:3])

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]

In [ ]:
import numpy as np
rand_arr= np.random.rand(3,2)
rand_arr

array([[0.00686768, 0.84321966],
       [0.62110974, 0.27133857],
       [0.04305348, 0.63996455]])

In [ ]:
rand_arr_int= np.random.randint(1,100,(3,3))
rand_arr_int

array([[28, 36, 65],
       [80,  5, 15],
       [85, 69,  3]])

In [ ]:
arr16=[2,55,77,44,11,-22,55,77,44,34,65,88]
arr16.append(2000)
arr16

[2, 55, 77, 44, 11, -22, 55, 77, 44, 34, 65, 88, 2000]

In [ ]:
arr16=np.append(arr16,321)

In [ ]:
arr16.insert(5,20001)
arr16

[2, 55, 77, 44, 11, 20001, 2000, -22, 55, 77, 44, 34, 65, 88, 2000]

In [ ]:
sorted_Arr=np.sort(arr16)
sorted_Arr

array([  -22,     2,    11,    34,    44,    44,    55,    55,    65,
          77,    77,    88,   321,  2000,  2000, 20001])

In [ ]:
np.split(arr16,2)

[array([    2,    55,    77,    44,    11, 20001,  2000,   -22]),
 array([  55,   77,   44,   34,   65,   88, 2000,  321])]

In [ ]:
arr_2d=[[1,2,3,4],
        [5,6,7,8],
        [9,8,7,6]]
arr_2d=np.insert(arr_2d,3,[[2],[4],[6],[8]],axis=0)
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6],
       [2, 2, 2, 2],
       [4, 4, 4, 4],
       [6, 6, 6, 6],
       [8, 8, 8, 8]])

In [ ]:
arr_2d=[[1,2,3,4],
        [5,6,7,8],
        [9,8,7,6]]
arr_2d=np.insert(arr_2d,3,[[2,4,6,8]],axis=0)
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6],
       [2, 4, 6, 8]])

In [ ]:
np.save("saved_array.npy",arr_2d)

In [ ]:
load_arr=np.load("saved_array.npy")
load_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6],
       [2, 4, 6, 8]])

In [ ]:
np.savetxt("saved_array1.txt",arr_2d)

In [ ]:
load_arr1=np.loadtxt("saved_array1.txt")
load_arr1

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.],
       [9., 8., 7., 6.],
       [2., 4., 6., 8.]])

In [ ]:
load_arr=np.loadtxt("saved_array.npy",delimiter=',')
load_arr

In [ ]:
arr_2d1=arr_2d>3
arr_2d1

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False,  True,  True,  True]])

In [ ]:
arr_2d1=arr_2d[arr_2d>6]
arr_2d1

array([7, 8, 9, 8, 7, 8])

In [ ]:
arr_2d.dtype

dtype('int64')

In [ ]:
arr_2d=arr_2d.astype("float")
arr_2d.dtype

dtype('float64')

In [ ]:
arr_2d*arr_2d

array([[ 1.,  4.,  9., 16.],
       [25., 36., 49., 64.],
       [81., 64., 49., 36.],
       [ 4., 16., 36., 64.]])

In [ ]:
np.sqrt(arr_2d)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 2.82842712, 2.64575131, 2.44948974],
       [1.41421356, 2.        , 2.44948974, 2.82842712]])

In [ ]:
arr_2d**arr_2d

array([[1.00000000e+00, 4.00000000e+00, 2.70000000e+01, 2.56000000e+02],
       [3.12500000e+03, 4.66560000e+04, 8.23543000e+05, 1.67772160e+07],
       [3.87420489e+08, 1.67772160e+07, 8.23543000e+05, 4.66560000e+04],
       [4.00000000e+00, 2.56000000e+02, 4.66560000e+04, 1.67772160e+07]])

In [ ]:
a=np.max(arr_2d)
a

np.float64(9.0)

In [ ]:
import numpy as np
import pandas as pd
arr=np.array([1,2,3,4,5])
series=pd.Series(arr,index=["a","b","c","d","e"])
series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
student_data={
    "Name":["Ali","Ahmad"],
    "Age":[22,33],
    "Gender":['M','M'],
    "Grade":["A","B"]
}
student_data

{'Name': ['Ali', 'Ahmad'],
 'Age': [22, 33],
 'Gender': ['M', 'M'],
 'Grade': ['A', 'B']}

In [ ]:
student_df=pd.DataFrame(student_data)
student_df

    Name  Age Gender Grade
0    Ali   22      M     A
1  Ahmad   33      M     B

In [ ]:
student_df["Name"]

0      Ali
1    Ahmad
Name: Name, dtype: object

In [ ]:
student_df[["Name","Grade"]]

    Name Grade
0    Ali     A
1  Ahmad     B

In [ ]:
student_df.loc[0:1]

    Name  Age Gender Grade
0    Ali   22      M     A
1  Ahmad   33      M     B

In [ ]:
student_df.iloc[0:1]

  Name  Age Gender Grade
0  Ali   22      M     A

In [ ]:
student_df.describe() #describe statistical

             Age
count   2.000000
mean   27.500000
std     7.778175
min    22.000000
25%    24.750000
50%    27.500000
75%    30.250000
max    33.000000

In [ ]:
student_df.dtypes

Name      object
Age        int64
Gender    object
Grade     object
dtype: object

In [ ]:
student_df.loc[0:1,["Name"]]

    Name
0    Ali
1  Ahmad

In [ ]:
student_df.iloc[0:2,[0,2]]

    Name Gender
0    Ali      M
1  Ahmad      M

In [ ]:
student_df.columns

Index(['Name', 'Age', 'Gender', 'Grade'], dtype='object')

In [ ]:
student_df.index

RangeIndex(start=0, stop=2, step=1)

In [ ]:
student_df.index.to_list()

[0, 1]

In [ ]:
student_df[student_df["Grade"]=='A']

  Name  Age Gender Grade
0  Ali   22      M     A

In [ ]:
student_df[student_df["Age"]>=10]

    Name  Age Gender Grade
0    Ali   22      M     A
1  Ahmad   33      M     B

In [ ]:
student_df[(student_df["Age"]>=18) & (student_df["Grade"]=='A')]

  Name  Age Gender Grade
0  Ali   22      M     A

In [ ]:
arr20=[10,20,30,40]
arr_df=pd.Series(arr20)
arr_df.index=["Q1","Q4","Q3","Q4"]

Q1    10
Q4    20
Q3    30
Q4    40
dtype: int64

In [ ]:
company={
    "Product_id":[22,33,44,66,77],
    "Item_name":["Dell","Hp","Acer","Lenevo","Mechrevo"],
    "Price":[2000,3000,4000,5000,6000],
    "Quatity":[2,4,6,8,10]
}
company_df=pd.DataFrame(company)
company_df.iloc[2:5]

   Product_id Item_name  Price  Quatity
2          44      Acer   4000        6
3          66    Lenevo   5000        8
4          77  Mechrevo   6000       10

Empty DataFrame
Columns: [Product_id, Item_name, Price, Quatity]
Index: []

In [ ]:
student_data={
    "Name":["Ali","Ahmad","Zeeshan","OOways"," "],
    "Age":[22,33,55,np.nan,np.nan],
    "Gender":['F','M','M',"M",np.nan],
    "Grade":["A","B","C",np.nan,np.nan]
}
student_data

{'Name': ['Ali', 'Ahmad', 'Zeeshan', 'OOways', ' '],
 'Age': [22, 33, 55, nan, nan],
 'Gender': ['F', 'M', 'M', 'M', nan],
 'Grade': ['A', 'B', 'C', nan, nan]}

In [ ]:
student_df=pd.DataFrame(student_data)
student_df

      Name   Age Gender Grade
0      Ali  22.0      F     A
1    Ahmad  33.0      M     B
2  Zeeshan  55.0      M     C
3   OOways   NaN      M   NaN
4            NaN    NaN   NaN

In [ ]:
#Finding null Values
student_df.isnull().sum()

Name      0
Age       2
Gender    1
Grade     2
dtype: int64

In [ ]:
student_df.dropna(inplace=False)

      Name   Age Gender Grade
0      Ali  22.0      M     A
1    Ahmad  33.0      M     B
2  Zeeshan  55.0      M     C

In [ ]:
mean_age=student_df["Age"].mean()

In [ ]:
#missing value 1 categorical= mode, numeric and nature is discrete= mode or median  3 numeric and continuou= mean mode

student_df["Age"]=student_df["Age"].fillna(mean_age)

In [ ]:
student_df["Gender"].fillna(student_df["Gender"].mode()[0])

0    F
1    M
2    M
3    M
4    M
Name: Gender, dtype: object

In [ ]:
student_df.dropna(thresh=5)

Empty DataFrame
Columns: [Name, Age, Gender, Grade]
Index: []

In [ ]:
student_df.ffill()

      Name   Age Gender Grade
0      Ali  22.0      F     A
1    Ahmad  33.0      M     B
2  Zeeshan  55.0      M     C
3   OOways  55.0      M     C
4           55.0      M     C

In [ ]:
import numpy as np
import pandas as pd

student_data={
    "Name":["Ali","Ahmad","Zeeshan","OOways",np.nan],
    "Age":[22,33,55,np.nan,np.nan],
    "Gender":['F','M','M',"M",np.nan]
}
student_df=pd.DataFrame(student_data)
student_data1={
    "Name":["Ali","Ahmad","Zeeshan","OOways",np.nan],
    "Age":[22,33,55,np.nan,np.nan],
    "Gender":['F','M','M',"M",np.nan]
}
student_df1=pd.DataFrame(student_data1)
pd.concat([student_df1,student_df],ignore_index=True)

      Name   Age Gender
0      Ali  22.0      F
1    Ahmad  33.0      M
2  Zeeshan  55.0      M
3   OOways   NaN      M
4      NaN   NaN    NaN
5      Ali  22.0      F
6    Ahmad  33.0      M
7  Zeeshan  55.0      M
8   OOways   NaN      M
9      NaN   NaN    NaN