<a href="https://colab.research.google.com/github/Uwais-ur-Rehman/ML-Project/blob/main/Third_day_of_Coding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating DataFrame using list

In [ ]:
import numpy as np
import pandas as pd

student_marks=[
    [77,88,77,66,77,87],
    [66,77,55,44,88,98],
    [98,87,89,90,87,66],
    [67,73,91,81,72,59]
]
marks=pd.DataFrame(student_marks,columns=['c++','python','java','c','php','Sql'])
print(marks)

   c++  python  java   c  php  Sql
0   77      88    77  66   77   87
1   66      77    55  44   88   98
2   98      87    89  90   87   66
3   67      73    91  81   72   59

In [ ]:
df_student_marks = pd.DataFrame(student_marks, columns=['c++','python','java','c','php','Sql'])
df_student_marks = df_student_marks.rename(columns={'c++':'C++','python':'PYTHON','java':'JAVA','c':'C','php':'PHP','Sql':'SQL'})
print(df_student_marks)

   C++  PYTHON  JAVA   C  PHP  SQL
0   77      88    77  66   77   87
1   66      77    55  44   88   98
2   98      87    89  90   87   66
3   67      73    91  81   72   59

Creating DataFrame using Dict

In [ ]:
student_marks1={
    'Name':['Ali','Ahmad','Ayesha','Adil','Adnan','Abeer'],
    'Java':[77,88,87,66,77,87],
    'C++':[67,73,91,81,72,59],
    'C':[66,77,86,94,88,98],
    'Python':[98,87,89,90,87,66],
    'Obtained':[0,0,0,0,0,0],
    'Total':[0,0,0,0,0,0],
    'Percentage':[0,0,0,0,0,0]
}
marks1=pd.DataFrame(student_marks1)
marks1.set_index('Name',inplace=True)
marks1['Obtained']=marks1[['Java','C++','C','Python']].sum(axis=1)
marks1['Total']=marks1[['Java','C++','C','Python']].count(axis=1)*100
marks1['Percentage']=(marks1['Obtained']/marks1['Total'])*100
print(marks1)
print(f"\n Marks:\n {marks1.loc[[marks1['Percentage'].idxmax()]]}\n")
print(marks1['Percentage'])

        Java  C++   C  Python  Obtained  Total  Percentage
Name
Ali       77   67  66      98       308    400       77.00
Ahmad     88   73  77      87       325    400       81.25
Ayesha    87   91  86      89       353    400       88.25
Adil      66   81  94      90       331    400       82.75
Adnan     77   72  88      87       324    400       81.00
Abeer     87   59  98      66       310    400       77.50

 Marks:
         Java  C++   C  Python  Obtained  Total  Percentage
Name
Ayesha    87   91  86      89       353    400       88.25

Name
Ali       77.00
Ahmad     81.25
Ayesha    88.25
Adil      82.75
Adnan     81.00
Abeer     77.50
Name: Percentage, dtype: float64

In [ ]:
def grade_cal(value):
  if value>=85:
    return "A"
  elif value>=75:
    return "B"
  elif value>=65:
    return "C"
  elif value>=55:
    return "D"
  elif value>=50:
    return "Pass"
  else:
    return "Fail"

In [ ]:
marks1['Grade']= marks1['Percentage'].apply(grade_cal)
print(marks1)

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (ipython-input-1975795742.py, line 1)

In [ ]:
marks1.value_counts()

Java  C++  C   Python  Obtained  Total  Percentage
66    81   94  90      331       400    82.75         1
77    67   66  98      308       400    77.00         1
      72   88  87      324       400    81.00         1
87    59   98  66      310       400    77.50         1
      91   86  89      353       400    88.25         1
88    73   77  87      325       400    81.25         1
Name: count, dtype: int64

In [ ]:
marks1.rename(columns={'C':'JavaScript'},inplace=True)
print(marks1)

        Java  C++  JavaScript  Python  Obtained  Total  Percentage
Name
Ali       77   67          66      98       308    400       77.00
Ahmad     88   73          77      87       325    400       81.25
Ayesha    87   91          86      89       353    400       88.25
Adil      66   81          94      90       331    400       82.75
Adnan     77   72          88      87       324    400       81.00
Abeer     87   59          98      66       310    400       77.50

In [ ]:
#marks1['Not a Number'].hasnans
#print(marks1['Not a Number'][marks1['Not a Number'].isnull()])
marks1.dropna(how='any')
print(marks1)

        Java   C++  JavaScript  Python  Obtained  Total  Percentage  \
Name
Ali     77.0  67.0        66.0    98.0     308.0  400.0       77.00
Ahmad   88.0  73.0        77.0    87.0     325.0  400.0       81.25
Ayesha  87.0  91.0        86.0    89.0     353.0  400.0       88.25
Adil    66.0  81.0        94.0    90.0     331.0  400.0       82.75
Adnan   77.0  72.0        88.0    87.0     324.0  400.0       81.00
Abeer   87.0  59.0        98.0    66.0     310.0  400.0       77.50
6        NaN   NaN         NaN     NaN       NaN    NaN         NaN
7        NaN   NaN         NaN     NaN       NaN    NaN         NaN
8        NaN   NaN         NaN     NaN       NaN    NaN         NaN

        Not a Number
Name
Ali              NaN
Ahmad            NaN
Ayesha           NaN
Adil             NaN
Adnan            NaN
Abeer            NaN
6                NaN
7                NaN
8                NaN

In [ ]:
marks1.dropna(how='all')

,level_0,index,Name,Java,C++,JavaScript,Python,Obtained,Total,Percentage,Not a Number
0,0,0,Ali,77.0,67.0,66.0,98.0,308.0,400.0,77.00,NaN
1,1,1,Ahmad,88.0,73.0,77.0,87.0,325.0,400.0,81.25,NaN
2,2,2,Ayesha,87.0,91.0,86.0,89.0,353.0,400.0,88.25,NaN
3,3,3,Adil,66.0,81.0,94.0,90.0,331.0,400.0,82.75,NaN
4,4,4,Adnan,77.0,72.0,88.0,87.0,324.0,400.0,81.00,NaN
5,5,5,Abeer,87.0,59.0,98.0,66.0,310.0,400.0,77.50,NaN
6,6,6,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,7,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,8,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,Adil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Adil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
marks1

        Java  C++   C  Python  Obtained  Total  Percentage
Name
Ali       77   67  66      98       308    400       77.00
Ahmad     88   73  77      87       325    400       81.25
Ayesha    87   91  86      89       353    400       88.25
Adil      66   81  94      90       331    400       82.75
Adnan     77   72  88      87       324    400       81.00
Abeer     87   59  98      66       310    400       77.50

In [ ]:
marks1.reset_index(inplace=True)
marks1.loc['Adil', 'Percentage'] = np.nan
marks1['Percentage'].fillna((marks1['Obtained']/marks1['Total'])*100,inplace=True)
print(marks1)

        Name  Java   C++     C  Python  Obtained  Total  Percentage
0        Ali  77.0  67.0  66.0    98.0     308.0  400.0       77.00
1      Ahmad  88.0  73.0  77.0    87.0     325.0  400.0       81.25
2     Ayesha  87.0  91.0  86.0    89.0     353.0  400.0       88.25
3       Adil  66.0  81.0  94.0    90.0     331.0  400.0       82.75
4      Adnan  77.0  72.0  88.0    87.0     324.0  400.0       81.00
5      Abeer  87.0  59.0  98.0    66.0     310.0  400.0       77.50
Adil     NaN   NaN   NaN   NaN     NaN       NaN    NaN         NaN

/tmp/ipython-input-194926206.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  marks1['Percentage'].fillna((marks1['Obtained']/marks1['Total'])*100,inplace=True)

In [ ]:
marks1

        Java  C++   C  Python  Obtained  Total  Percentage
Name
Ali       77   67  66      98       308    400       77.00
Ahmad     88   73  77      87       325    400       81.25
Ayesha    87   91  86      89       353    400       88.25
Adil      66   81  94      90       331    400       82.75
Adnan     77   72  88      87       324    400       81.00
Abeer     87   59  98      66       310    400       77.50

In [ ]:
print("Using iloc \n")
print(marks1.iloc[1:4,4:7])
print("\n Using loc \n")
marks1.loc['Adil':'Adnan',['Obtained','Total','Percentage']]

Using iloc

        Obtained  Total  Percentage
Name
Ahmad        325    400       81.25
Ayesha       353    400       88.25
Adil         331    400       82.75

 Using loc

       Obtained  Total  Percentage
Name
Adil        331    400       82.75
Adnan       324    400       81.00

Using Reading csv

In [ ]:
salary=pd.read_csv('Salary.csv')
print(salary)

salary1=pd.read_csv('/content/Salary.csv')
print(f"Series:\n{salary1}")

NameError: name 'pd' is not defined

In [ ]:
psl=pd.read_csv('psl.csv')
psl.shape
#psl.dtypes
#psl.index
#psl.columns
#psl.values
#psl.info()

(66112, 27)

In [ ]:
psl.describe()

,id,match_id,season,inning,over,ball,batsman_runs,extra_runs,total_runs
count,54033.000000,5.403300e+04,54032.000000,54032.000000,54032.000000,54032.000000,54032.000000,54032.000000,54032.000000
mean,234.879740,1.223634e+06,2020.257681,1.482418,10.128387,3.616561,1.287034,0.069699,1.356733
std,97.241084,9.050724e+04,2.006344,0.503239,5.655003,1.811436,1.661625,0.357086,1.649280
min,1.000000,1.416400e+04,2017.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,165.000000,1.168821e+06,2019.000000,1.000000,5.000000,2.000000,0.000000,0.000000,0.000000
50%,234.000000,1.211670e+06,2020.000000,1.000000,10.000000,4.000000,1.000000,0.000000,1.000000
75%,304.000000,1.293017e+06,2022.000000,2.000000,15.000000,5.000000,1.000000,0.000000,1.000000
max,482.000000,1.416476e+06,2024.000000,4.000000,20.000000,11.000000,6.000000,5.000000,7.000000

In [ ]:
psl['date'].hasnans

False

In [ ]:
psl.isnull().sum()

id                      0
match_id                0
date                    0
season                  0
venue                   0
inning                  0
batting_team            0
bowling_team            0
over                    0
ball                    0
batter                  0
bowler                  0
non_striker             0
batsman_runs            0
extra_runs              0
total_runs              0
extras_type         62551
is_wicket               0
player_dismissed    62608
dismissal_kind      62608
fielder             63811
winner                  0
win_by                  0
match_type              0
player_of_match       664
umpire_1                0
umpire_2                0
dtype: int64

In [ ]:
psl.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
54028    False
54029    False
54030    False
54031    False
54032    False
Length: 54033, dtype: bool

In [ ]:
psl.duplicated().sum()

np.int64(0)

In [ ]:
final1=psl['match_type']=='final'
final_session=psl[final1]
final_unique=final_session.drop_duplicates(subset='season')
print(final_unique[['season','winner']])

       season             winner
5193     2017     Peshawar Zalmi
12945    2018   Islamabad United
21017    2019  Quetta Gladiators
28131    2020      Karachi Kings

In [ ]:
psl[(psl['winner']=='Islamabad United') & (psl['venue']=='Dubai International Cricket Stadium')]

,id,match_id,date,season,venue,inning,batting_team,bowling_team,over,ball,...,is_wicket,player_dismissed,dismissal_kind,fielder,winner,win_by,match_type,player_of_match,umpire_1,umpire_2
0,1,1075986,2017-02-09,2017,Dubai International Cricket Stadium,1,Peshawar Zalmi,Islamabad United,1.0,1.0,...,True,Mohammad Hafeez,caught,Sharjeel Khan,Islamabad United,wickets 7,regular,BJ Haddin,Ahsan Raza,Shozab Raza
1,2,1075986,2017-02-09,2017,Dubai International Cricket Stadium,1,Peshawar Zalmi,Islamabad United,1.0,2.0,...,False,NaN,NaN,NaN,Islamabad United,wickets 7,regular,BJ Haddin,Ahsan Raza,Shozab Raza
2,3,1075986,2017-02-09,2017,Dubai International Cricket Stadium,1,Peshawar Zalmi,Islamabad United,1.0,3.0,...,False,NaN,NaN,NaN,Islamabad United,wickets 7,regular,BJ Haddin,Ahsan Raza,Shozab Raza
3,4,1075986,2017-02-09,2017,Dubai International Cricket Stadium,1,Peshawar Zalmi,Islamabad United,1.0,4.0,...,False,NaN,NaN,NaN,Islamabad United,wickets 7,regular,BJ Haddin,Ahsan Raza,Shozab Raza
4,5,1075986,2017-02-09,2017,Dubai International Cricket Stadium,1,Peshawar Zalmi,Islamabad United,1.0,5.0,...,False,NaN,NaN,NaN,Islamabad United,wickets 7,regular,BJ Haddin,Ahsan Raza,Shozab Raza
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17391,312,1168837,2019-02-27,2019,Dubai International Cricket Stadium,2,Islamabad United,Karachi Kings,19.0,5.0,...,False,NaN,NaN,NaN,Islamabad United,wickets 5,regular,Asif Ali,RK Illingworth,Ahsan Raza
17392,313,1168837,2019-02-27,2019,Dubai International Cricket Stadium,2,Islamabad United,Karachi Kings,19.0,6.0,...,False,NaN,NaN,NaN,Islamabad United,wickets 5,regular,Asif Ali,RK Illingworth,Ahsan Raza
17393,314,1168837,2019-02-27,2019,Dubai International Cricket Stadium,2,Islamabad United,Karachi Kings,19.0,7.0,...,False,NaN,NaN,NaN,Islamabad United,wickets 5,regular,Asif Ali,RK Illingworth,Ahsan Raza
17394,315,1168837,2019-02-27,2019,Dubai International Cricket Stadium,2,Islamabad United,Karachi Kings,20.0,1.0,...,False,NaN,NaN,NaN,Islamabad United,wickets 5,regular,Asif Ali,RK Illingworth,Ahsan Raza
17395,316,1168837,2019-02-27,2019,Dubai International Cricket Stadium,2,Islamabad United,Karachi Kings,20.0,2.0,...,False,NaN,NaN,NaN,Islamabad United,wickets 5,regular,Asif Ali,RK Illingworth,Ahsan Raza

In [ ]:
psl.value_counts()

id   match_id  date        season  venue                                inning  batting_team       bowling_team       over  ball  batter           bowler          non_striker      batsman_runs  extra_runs  total_runs  extras_type  is_wicket  player_dismissed  dismissal_kind  fielder          winner            win_by     match_type  player_of_match  umpire_1       umpire_2
95   1076009   2017-03-05  2017    Gaddafi Stadium                      1       Peshawar Zalmi     Quetta Gladiators  12    4     Khushdil Shah    Hassan Khan     Mohammad Hafeez  0             1           1           wides        True       Khushdil Shah     stumped         Sarfraz Ahmed    Peshawar Zalmi    runs 58    final       DJG Sammy        Ahsan Raza     REJ Martinesz     1
261  1247026   2021-06-10  2021    Sheikh Zayed Stadium, Abu Dhabi      1       Lahore Qalandars   Peshawar Zalmi     20    6     TH David         Umaid Asif      Ahmed Daniyal    0             1           1           wides        True       Ahmed Daniyal     run out         Kamran Akmal     Lahore Qalandars  runs 10    regular     Rashid Khan      Asif Yaqoob    Rashid Riaz       1
264  1168848   2019-03-10  2019    National Stadium                     2       Quetta Gladiators  Karachi Kings      9     5     RR Rossouw       Umer Khan       Ahmed Shehzad    0             1           1           wides        True       RR Rossouw        stumped         BR Dunk          Karachi Kings     runs 1     regular     Usman Shinwari   REJ Martinesz  Asif Yaqoob       1
267  1247031   2021-06-13  2021    Sheikh Zayed Stadium, Abu Dhabi      1       Peshawar Zalmi     Multan Sultans     20    5     SE Rutherford    Imran Khan      FA Allen         0             1           1           legbyes      True       SE Rutherford     run out         Mohammad Rizwan  Multan Sultans    wickets 8  regular     Shahnawaz Dhani  Ahsan Raza     Aleem Dar         1
268  1247031   2021-06-13  2021    Sheikh Zayed Stadium, Abu Dhabi      1       Peshawar Zalmi     Multan Sultans     20    6     Wahab Riaz       Imran Khan      FA Allen         0             1           1           wides        True       FA Allen          run out         Mohammad Rizwan  Multan Sultans    wickets 8  regular     Shahnawaz Dhani  Ahsan Raza     Aleem Dar         1
281  1354951   2023-03-11  2023    Rawalpindi Cricket Stadium           1       Multan Sultans     Quetta Gladiators  11    1     Usman Khan       Mohammad Nawaz  Mohammad Rizwan  0             1           1           wides        True       Usman Khan        stumped         Umar Akmal       Multan Sultans    runs 9     regular     Abbas Afridi     AG Wharf       MJ Saggers        1
334  1247034   2021-06-15  2021    Sheikh Zayed Stadium, Abu Dhabi      2       Peshawar Zalmi     Karachi Kings      10    1     Haider Ali       Noor Ahmad      R Powell         0             1           1           wides        True       Haider Ali        stumped         CAK Walton       Peshawar Zalmi    wickets 6  regular     Hazratullah      Ahsan Raza     Shozab Raza       1
366  1293000   2022-01-27  2022    National Stadium, Karachi            2       Multan Sultans     Karachi Kings      15    2     Sohaib Maqsood   Mohammad Nabi   Mohammad Rizwan  0             1           1           wides        True       Sohaib Maqsood    stumped         JM Clarke        Multan Sultans    wickets 7  regular     Imran Tahir      Aleem Dar      RK Illingworth    1
488  959189    2016-02-08  2016    Dubai International Cricket Stadium  2       Quetta Gladiators  Lahore Qalandars   17    1     Akbar-ur-Rehman  Zafar Gohar     Umar Gul         0             1           1           wides        True       Akbar-ur-Rehman   stumped         Mohammad Rizwan  Lahore Qalandars  runs 63    regular     Umar Akmal       JS Wilson      Aleem Dar         1
Name: count, dtype: int64

In [ ]:
print(psl['season'].unique())
#print(len(psl['season'].unique()))
print(psl['season'].nunique())

NameError: name 'psl' is not defined

In [ ]:
match_filter=psl[(psl['match_type']=='qualifier') | (psl['match_type']=='final')]
match_winner= match_filter['player_of_match'].value_counts().head(1)
print(f"most player of the match: {match_winner}")

most player of the match: player_of_match
Babar Azam    499
Name: count, dtype: int64

In [ ]:
runs= psl['batter']
most_runs=runs.value_counts()
print(f"most runs: {most_runs}")

most runs: batter
Babar Azam           2822
Mohammad Rizwan      1949
Shoaib Malik         1878
Fakhar Zaman         1852
RR Rossouw           1456
                     ...
Saifullah Bangash       1
Mehran Mumtaz           1
JA Thompson             1
AJ Tye                  1
Zeeshan Zameer          1
Name: count, Length: 342, dtype: int64

In [ ]:
psl_match1=psl['batting_team']
total_matches1=psl_match1.value_counts()
psl_match2=psl['bowling_team']
total_matches2=psl_match2.value_counts()
print(f"\n batting matches \n: {total_matches1} \n")
print(f"\nbowling matches: {total_matches2.sort_values(ascending=True)}\n")
print(f"\ntotal matches: {total_matches1+total_matches2}\n")

 batting matches
: batting_team
Peshawar Zalmi       12291
Islamabad United     11581
Lahore Qalandars     11158
Karachi Kings        11044
Quetta Gladiators    10743
Multan Sultans        9295
Name: count, dtype: int64


bowling matches: bowling_team
Multan Sultans        9096
Quetta Gladiators    10945
Karachi Kings        10949
Lahore Qalandars     11155
Islamabad United     11884
Peshawar Zalmi       12083
Name: count, dtype: int64


total matches: batting_team
Peshawar Zalmi       24374
Islamabad United     23465
Lahore Qalandars     22313
Karachi Kings        21993
Quetta Gladiators    21688
Multan Sultans       18391
Name: count, dtype: int64

In [ ]:
most_runs.rank()

batter
Babar Azam           342.0
Mohammad Rizwan      341.0
Shoaib Malik         340.0
Fakhar Zaman         339.0
RR Rossouw           338.0
                     ...
Saifullah Bangash      7.5
Mehran Mumtaz          7.5
JA Thompson            7.5
AJ Tye                 7.5
Zeeshan Zameer         7.5
Name: count, Length: 342, dtype: float64

In [ ]:
psl['Batsman_Rank']=most_runs.rank()
print(psl['Batsman_Rank'])

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
66107   NaN
66108   NaN
66109   NaN
66110   NaN
66111   NaN
Name: Batsman_Rank, Length: 66112, dtype: float64

In [ ]:
print(psl)

        id  match_id        date  season                                venue  \
0        1   1075986  2017-02-09    2017  Dubai International Cricket Stadium
1        2   1075986  2017-02-09    2017  Dubai International Cricket Stadium
2        3   1075986  2017-02-09    2017  Dubai International Cricket Stadium
3        4   1075986  2017-02-09    2017  Dubai International Cricket Stadium
4        5   1075986  2017-02-09    2017  Dubai International Cricket Stadium
...    ...       ...         ...     ...                                  ...
66107  507    959221  2016-02-23    2016  Dubai International Cricket Stadium
66108  508    959221  2016-02-23    2016  Dubai International Cricket Stadium
66109  509    959221  2016-02-23    2016  Dubai International Cricket Stadium
66110  510    959221  2016-02-23    2016  Dubai International Cricket Stadium
66111  511    959221  2016-02-23    2016  Dubai International Cricket Stadium

       inning      batting_team       bowling_team  over  ball  ...  \
0           1    Peshawar Zalmi   Islamabad United     1     1  ...
1           1    Peshawar Zalmi   Islamabad United     1     2  ...
2           1    Peshawar Zalmi   Islamabad United     1     3  ...
3           1    Peshawar Zalmi   Islamabad United     1     4  ...
4           1    Peshawar Zalmi   Islamabad United     1     5  ...
...       ...               ...                ...   ...   ...  ...
66107       2  Islamabad United  Quetta Gladiators    18     6  ...
66108       2  Islamabad United  Quetta Gladiators    19     1  ...
66109       2  Islamabad United  Quetta Gladiators    19     2  ...
66110       2  Islamabad United  Quetta Gladiators    19     3  ...
66111       2  Islamabad United  Quetta Gladiators    19     4  ...

      player_dismissed dismissal_kind         fielder            winner  \
0      Mohammad Hafeez         caught   Sharjeel Khan  Islamabad United
1                  NaN            NaN             NaN  Islamabad United
2                  NaN            NaN             NaN  Islamabad United
3                  NaN            NaN             NaN  Islamabad United
4                  NaN            NaN             NaN  Islamabad United
...                ...            ...             ...               ...
66107              NaN            NaN             NaN  Islamabad United
66108              NaN            NaN             NaN  Islamabad United
66109     Khalid Latif         caught  Zulfiqar Babar  Islamabad United
66110              NaN            NaN             NaN  Islamabad United
66111              NaN            NaN             NaN  Islamabad United

          win_by  match_type player_of_match    umpire_1     umpire_2  \
0      wickets 7     regular       BJ Haddin  Ahsan Raza  Shozab Raza
1      wickets 7     regular       BJ Haddin  Ahsan Raza  Shozab Raza
2      wickets 7     regular       BJ Haddin  Ahsan Raza  Shozab Raza
3      wickets 7     regular       BJ Haddin  Ahsan Raza  Shozab Raza
4      wickets 7     regular       BJ Haddin  Ahsan Raza  Shozab Raza
...          ...         ...             ...         ...          ...
66107  wickets 6       final        DR Smith   JS Wilson    Aleem Dar
66108  wickets 6       final        DR Smith   JS Wilson    Aleem Dar
66109  wickets 6       final        DR Smith   JS Wilson    Aleem Dar
66110  wickets 6       final        DR Smith   JS Wilson    Aleem Dar
66111  wickets 6       final        DR Smith   JS Wilson    Aleem Dar

      Batsman_Rank
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
...            ...
66107          NaN
66108          NaN
66109          NaN
66110          NaN
66111          NaN

[66112 rows x 28 columns]